/*
XYO RESTful Transaction Enrichment API

RESTful API for enriching financial transactions.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// EnrichmentAPIService EnrichmentAPI service
type EnrichmentAPIService service

type ApiEnrichTransactionRequest struct {
	ctx               context.Context
	ApiService        *EnrichmentAPIService
	enrichmentRequest *EnrichmentRequest
	xCorrelationID    *string
	traceparent       *string
}

// Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.
func (r ApiEnrichTransactionRequest) EnrichmentRequest(enrichmentRequest EnrichmentRequest) ApiEnrichTransactionRequest {
	r.enrichmentRequest = &enrichmentRequest
	return r
}

// Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
func (r ApiEnrichTransactionRequest) XCorrelationID(xCorrelationID string) ApiEnrichTransactionRequest {
	r.xCorrelationID = &xCorrelationID
	return r
}

// Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
func (r ApiEnrichTransactionRequest) Traceparent(traceparent string) ApiEnrichTransactionRequest {
	r.traceparent = &traceparent
	return r
}

func (r ApiEnrichTransactionRequest) Execute() (*EnrichmentResponse, *http.Response, error) {
	return r.ApiService.EnrichTransactionExecute(r)
}

/*
EnrichTransaction Transaction Enrichment

Enrich a single financial transaction synchronously.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiEnrichTransactionRequest
*/
func (a *EnrichmentAPIService) EnrichTransaction(ctx context.Context) ApiEnrichTransactionRequest {
	return ApiEnrichTransactionRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return EnrichmentResponse
func (a *EnrichmentAPIService) EnrichTransactionExecute(r ApiEnrichTransactionRequest) (*EnrichmentResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *EnrichmentResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EnrichmentAPIService.EnrichTransaction")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/ai/finance/enrichment/transaction"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.enrichmentRequest == nil {
		return localVarReturnValue, nil, reportError("enrichmentRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCorrelationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Correlation-ID", r.xCorrelationID, "simple", "")
	}
	if r.traceparent != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "traceparent", r.traceparent, "simple", "")
	}
	// body params
	localVarPostBody = r.enrichmentRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(io.LimitReader(localVarHTTPResponse.Body, 32*1024*1024))
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 300 && localVarHTTPResponse.StatusCode < 400 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEnrichTransactionsRequest struct {
	ctx                            context.Context
	ApiService                     *EnrichmentAPIService
	enrichTransactionsRequestInner *[]EnrichTransactionsRequestInner
	xApiUser                       *string
	xCorrelationID                 *string
	traceparent                    *string
}

// Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.
func (r ApiEnrichTransactionsRequest) EnrichTransactionsRequestInner(enrichTransactionsRequestInner []EnrichTransactionsRequestInner) ApiEnrichTransactionsRequest {
	r.enrichTransactionsRequestInner = &enrichTransactionsRequestInner
	return r
}

// Optional identifier for the API user or tenant.
func (r ApiEnrichTransactionsRequest) XApiUser(xApiUser string) ApiEnrichTransactionsRequest {
	r.xApiUser = &xApiUser
	return r
}

// Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
func (r ApiEnrichTransactionsRequest) XCorrelationID(xCorrelationID string) ApiEnrichTransactionsRequest {
	r.xCorrelationID = &xCorrelationID
	return r
}

// Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
func (r ApiEnrichTransactionsRequest) Traceparent(traceparent string) ApiEnrichTransactionsRequest {
	r.traceparent = &traceparent
	return r
}

func (r ApiEnrichTransactionsRequest) Execute() (*EnrichTransactionCollectionResponse, *http.Response, error) {
	return r.ApiService.EnrichTransactionsExecute(r)
}

/*
EnrichTransactions Transaction Enrichments

Enrich a collection of financial transactions asynchronously.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiEnrichTransactionsRequest
*/
func (a *EnrichmentAPIService) EnrichTransactions(ctx context.Context) ApiEnrichTransactionsRequest {
	return ApiEnrichTransactionsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return EnrichTransactionCollectionResponse
func (a *EnrichmentAPIService) EnrichTransactionsExecute(r ApiEnrichTransactionsRequest) (*EnrichTransactionCollectionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *EnrichTransactionCollectionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EnrichmentAPIService.EnrichTransactions")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/ai/finance/enrichment/transactions"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.enrichTransactionsRequestInner == nil {
		return localVarReturnValue, nil, reportError("enrichTransactionsRequestInner is required and must be specified")
	}
	if len(*r.enrichTransactionsRequestInner) < 1 {
		return localVarReturnValue, nil, reportError("enrichTransactionsRequestInner must have at least 1 elements")
	}
	if len(*r.enrichTransactionsRequestInner) > 50000 {
		return localVarReturnValue, nil, reportError("enrichTransactionsRequestInner must have less than 50000 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiUser != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-user", r.xApiUser, "simple", "")
	}
	if r.xCorrelationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Correlation-ID", r.xCorrelationID, "simple", "")
	}
	if r.traceparent != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "traceparent", r.traceparent, "simple", "")
	}
	// body params
	localVarPostBody = r.enrichTransactionsRequestInner
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(io.LimitReader(localVarHTTPResponse.Body, 32*1024*1024))
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 300 && localVarHTTPResponse.StatusCode < 400 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetEnrichmentStatusRequest struct {
	ctx            context.Context
	ApiService     *EnrichmentAPIService
	id             string
	xApiUser       *string
	xCorrelationID *string
	traceparent    *string
}

// Optional identifier for the API user or tenant.
func (r ApiGetEnrichmentStatusRequest) XApiUser(xApiUser string) ApiGetEnrichmentStatusRequest {
	r.xApiUser = &xApiUser
	return r
}

// Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
func (r ApiGetEnrichmentStatusRequest) XCorrelationID(xCorrelationID string) ApiGetEnrichmentStatusRequest {
	r.xCorrelationID = &xCorrelationID
	return r
}

// Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
func (r ApiGetEnrichmentStatusRequest) Traceparent(traceparent string) ApiGetEnrichmentStatusRequest {
	r.traceparent = &traceparent
	return r
}

func (r ApiGetEnrichmentStatusRequest) Execute() (*EnrichmentCollectionStatusResponse, *http.Response, error) {
	return r.ApiService.GetEnrichmentStatusExecute(r)
}

/*
GetEnrichmentStatus Transaction Enrichments Status

Get the status of an asynchronous bulk enrichment job.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id The unique identifier of the asynchronous bulk enrichment job.
	@return ApiGetEnrichmentStatusRequest
*/
func (a *EnrichmentAPIService) GetEnrichmentStatus(ctx context.Context, id string) ApiGetEnrichmentStatusRequest {
	return ApiGetEnrichmentStatusRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return EnrichmentCollectionStatusResponse
func (a *EnrichmentAPIService) GetEnrichmentStatusExecute(r ApiGetEnrichmentStatusRequest) (*EnrichmentCollectionStatusResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *EnrichmentCollectionStatusResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EnrichmentAPIService.GetEnrichmentStatus")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/ai/finance/enrichment/status/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiUser != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-user", r.xApiUser, "simple", "")
	}
	if r.xCorrelationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Correlation-ID", r.xCorrelationID, "simple", "")
	}
	if r.traceparent != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "traceparent", r.traceparent, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(io.LimitReader(localVarHTTPResponse.Body, 32*1024*1024))
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 300 && localVarHTTPResponse.StatusCode < 400 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
