/*
XYO RESTful Transaction Enrichment API

RESTful API for enriching financial transactions.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the EnrichmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnrichmentResponse{}

// EnrichmentResponse struct for EnrichmentResponse
type EnrichmentResponse struct {
	// Merchant is the name of the merchant.
	Merchant string `json:"merchant"`
	// Description is a brief description of the merchant.
	Description string `json:"description"`
	// Categories lists categories fitting the description of the merchant.
	Categories []string `json:"categories"`
	// Logo is a base64-encoded PNG or JPEG representing the merchant logo.
	Logo string `json:"logo"`
	// Location describes the country and city. May be empty if the API returns null.
	Location string `json:"location"`
	// Address describes the exact address of purchase. May be empty if the API returns null.
	Address              string `json:"address"`
	AdditionalProperties map[string]interface{}
}

type _EnrichmentResponse EnrichmentResponse

// NewEnrichmentResponse instantiates a new EnrichmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrichmentResponse(merchant string, description string, categories []string, logo string, location string, address string) *EnrichmentResponse {
	this := EnrichmentResponse{}
	this.Merchant = merchant
	this.Description = description
	this.Categories = categories
	this.Logo = logo
	this.Location = location
	this.Address = address
	return &this
}

// NewEnrichmentResponseWithDefaults instantiates a new EnrichmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrichmentResponseWithDefaults() *EnrichmentResponse {
	this := EnrichmentResponse{}
	return &this
}

// GetMerchant returns the Merchant field value
func (o *EnrichmentResponse) GetMerchant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Merchant
}

// GetMerchantOk returns a tuple with the Merchant field value
// and a boolean to check if the value has been set.
func (o *EnrichmentResponse) GetMerchantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Merchant, true
}

// SetMerchant sets field value
func (o *EnrichmentResponse) SetMerchant(v string) {
	o.Merchant = v
}

// GetDescription returns the Description field value
func (o *EnrichmentResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *EnrichmentResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *EnrichmentResponse) SetDescription(v string) {
	o.Description = v
}

// GetCategories returns the Categories field value
func (o *EnrichmentResponse) GetCategories() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *EnrichmentResponse) GetCategoriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *EnrichmentResponse) SetCategories(v []string) {
	o.Categories = v
}

// GetLogo returns the Logo field value
func (o *EnrichmentResponse) GetLogo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Logo
}

// GetLogoOk returns a tuple with the Logo field value
// and a boolean to check if the value has been set.
func (o *EnrichmentResponse) GetLogoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Logo, true
}

// SetLogo sets field value
func (o *EnrichmentResponse) SetLogo(v string) {
	o.Logo = v
}

// GetLocation returns the Location field value
func (o *EnrichmentResponse) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *EnrichmentResponse) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *EnrichmentResponse) SetLocation(v string) {
	o.Location = v
}

// GetAddress returns the Address field value
func (o *EnrichmentResponse) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *EnrichmentResponse) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *EnrichmentResponse) SetAddress(v string) {
	o.Address = v
}

func (o EnrichmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnrichmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["merchant"] = o.Merchant
	toSerialize["description"] = o.Description
	toSerialize["categories"] = o.Categories
	toSerialize["logo"] = o.Logo
	toSerialize["location"] = o.Location
	toSerialize["address"] = o.Address

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EnrichmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"merchant",
		"description",
		"categories",
		"logo",
		"location",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnrichmentResponse := _EnrichmentResponse{}

	err = json.Unmarshal(data, &varEnrichmentResponse)

	if err != nil {
		return err
	}

	*o = EnrichmentResponse(varEnrichmentResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "merchant")
		delete(additionalProperties, "description")
		delete(additionalProperties, "categories")
		delete(additionalProperties, "logo")
		delete(additionalProperties, "location")
		delete(additionalProperties, "address")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEnrichmentResponse struct {
	value *EnrichmentResponse
	isSet bool
}

func (v NullableEnrichmentResponse) Get() *EnrichmentResponse {
	return v.value
}

func (v *NullableEnrichmentResponse) Set(val *EnrichmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrichmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrichmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrichmentResponse(val *EnrichmentResponse) *NullableEnrichmentResponse {
	return &NullableEnrichmentResponse{value: val, isSet: true}
}

func (v NullableEnrichmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrichmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
