/*
XYO RESTful Transaction Enrichment API

RESTful API for enriching financial transactions.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the EnrichmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnrichmentRequest{}

// EnrichmentRequest struct for EnrichmentRequest
type EnrichmentRequest struct {
	// Content is the payment description, maximum 128 characters.
	Content string `json:"content"`
	// CountryCode is the ISO 3166-1 alpha-2 two-character country code.
	CountryCode          string `json:"countryCode"`
	AdditionalProperties map[string]interface{}
}

type _EnrichmentRequest EnrichmentRequest

// NewEnrichmentRequest instantiates a new EnrichmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrichmentRequest(content string, countryCode string) *EnrichmentRequest {
	this := EnrichmentRequest{}
	this.Content = content
	this.CountryCode = countryCode
	return &this
}

// NewEnrichmentRequestWithDefaults instantiates a new EnrichmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrichmentRequestWithDefaults() *EnrichmentRequest {
	this := EnrichmentRequest{}
	return &this
}

// GetContent returns the Content field value
func (o *EnrichmentRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *EnrichmentRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *EnrichmentRequest) SetContent(v string) {
	o.Content = v
}

// GetCountryCode returns the CountryCode field value
func (o *EnrichmentRequest) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *EnrichmentRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *EnrichmentRequest) SetCountryCode(v string) {
	o.CountryCode = v
}

func (o EnrichmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnrichmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	toSerialize["countryCode"] = o.CountryCode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EnrichmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
		"countryCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnrichmentRequest := _EnrichmentRequest{}

	err = json.Unmarshal(data, &varEnrichmentRequest)

	if err != nil {
		return err
	}

	*o = EnrichmentRequest(varEnrichmentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "content")
		delete(additionalProperties, "countryCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEnrichmentRequest struct {
	value *EnrichmentRequest
	isSet bool
}

func (v NullableEnrichmentRequest) Get() *EnrichmentRequest {
	return v.value
}

func (v *NullableEnrichmentRequest) Set(val *EnrichmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrichmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrichmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrichmentRequest(val *EnrichmentRequest) *NullableEnrichmentRequest {
	return &NullableEnrichmentRequest{value: val, isSet: true}
}

func (v NullableEnrichmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrichmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
