/*
XYO RESTful Transaction Enrichment API

RESTful API for enriching financial transactions.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the EnrichTransactionCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnrichTransactionCollectionResponse{}

// EnrichTransactionCollectionResponse struct for EnrichTransactionCollectionResponse
type EnrichTransactionCollectionResponse struct {
	// ID is the work ID for the enrichment request.
	Id string `json:"id"`
	// Link is the URL to the downloadable tar.gz results archive.
	Link                 string `json:"link"`
	AdditionalProperties map[string]interface{}
}

type _EnrichTransactionCollectionResponse EnrichTransactionCollectionResponse

// NewEnrichTransactionCollectionResponse instantiates a new EnrichTransactionCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrichTransactionCollectionResponse(id string, link string) *EnrichTransactionCollectionResponse {
	this := EnrichTransactionCollectionResponse{}
	this.Id = id
	this.Link = link
	return &this
}

// NewEnrichTransactionCollectionResponseWithDefaults instantiates a new EnrichTransactionCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrichTransactionCollectionResponseWithDefaults() *EnrichTransactionCollectionResponse {
	this := EnrichTransactionCollectionResponse{}
	return &this
}

// GetId returns the Id field value
func (o *EnrichTransactionCollectionResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EnrichTransactionCollectionResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EnrichTransactionCollectionResponse) SetId(v string) {
	o.Id = v
}

// GetLink returns the Link field value
func (o *EnrichTransactionCollectionResponse) GetLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Link
}

// GetLinkOk returns a tuple with the Link field value
// and a boolean to check if the value has been set.
func (o *EnrichTransactionCollectionResponse) GetLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Link, true
}

// SetLink sets field value
func (o *EnrichTransactionCollectionResponse) SetLink(v string) {
	o.Link = v
}

func (o EnrichTransactionCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnrichTransactionCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["link"] = o.Link

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EnrichTransactionCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"link",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnrichTransactionCollectionResponse := _EnrichTransactionCollectionResponse{}

	err = json.Unmarshal(data, &varEnrichTransactionCollectionResponse)

	if err != nil {
		return err
	}

	*o = EnrichTransactionCollectionResponse(varEnrichTransactionCollectionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "link")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEnrichTransactionCollectionResponse struct {
	value *EnrichTransactionCollectionResponse
	isSet bool
}

func (v NullableEnrichTransactionCollectionResponse) Get() *EnrichTransactionCollectionResponse {
	return v.value
}

func (v *NullableEnrichTransactionCollectionResponse) Set(val *EnrichTransactionCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrichTransactionCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrichTransactionCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrichTransactionCollectionResponse(val *EnrichTransactionCollectionResponse) *NullableEnrichTransactionCollectionResponse {
	return &NullableEnrichTransactionCollectionResponse{value: val, isSet: true}
}

func (v NullableEnrichTransactionCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrichTransactionCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
