/*
XYO RESTful Transaction Enrichment API

RESTful API for enriching financial transactions.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the EnrichmentCollectionStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnrichmentCollectionStatusResponse{}

// EnrichmentCollectionStatusResponse struct for EnrichmentCollectionStatusResponse
type EnrichmentCollectionStatusResponse struct {
	// Status represents the processing state of a bulk enrichment job.
	Status               string `json:"status"`
	AdditionalProperties map[string]interface{}
}

type _EnrichmentCollectionStatusResponse EnrichmentCollectionStatusResponse

// NewEnrichmentCollectionStatusResponse instantiates a new EnrichmentCollectionStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrichmentCollectionStatusResponse(status string) *EnrichmentCollectionStatusResponse {
	this := EnrichmentCollectionStatusResponse{}
	this.Status = status
	return &this
}

// NewEnrichmentCollectionStatusResponseWithDefaults instantiates a new EnrichmentCollectionStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrichmentCollectionStatusResponseWithDefaults() *EnrichmentCollectionStatusResponse {
	this := EnrichmentCollectionStatusResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *EnrichmentCollectionStatusResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EnrichmentCollectionStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EnrichmentCollectionStatusResponse) SetStatus(v string) {
	o.Status = v
}

func (o EnrichmentCollectionStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnrichmentCollectionStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EnrichmentCollectionStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnrichmentCollectionStatusResponse := _EnrichmentCollectionStatusResponse{}

	err = json.Unmarshal(data, &varEnrichmentCollectionStatusResponse)

	if err != nil {
		return err
	}

	*o = EnrichmentCollectionStatusResponse(varEnrichmentCollectionStatusResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEnrichmentCollectionStatusResponse struct {
	value *EnrichmentCollectionStatusResponse
	isSet bool
}

func (v NullableEnrichmentCollectionStatusResponse) Get() *EnrichmentCollectionStatusResponse {
	return v.value
}

func (v *NullableEnrichmentCollectionStatusResponse) Set(val *EnrichmentCollectionStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrichmentCollectionStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrichmentCollectionStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrichmentCollectionStatusResponse(val *EnrichmentCollectionStatusResponse) *NullableEnrichmentCollectionStatusResponse {
	return &NullableEnrichmentCollectionStatusResponse{value: val, isSet: true}
}

func (v NullableEnrichmentCollectionStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrichmentCollectionStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
